# Generated by Django 2.1.15 on 2020-07-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanphoto',
            name='title',
        ),
    ]
